services:
  server:
    build: .
    env_file: 
      - app-example.env
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    env_file: 
      - db-example.env
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 1s
      retries: 5